config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise users method
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }, path_prefix: 'new'
  devise_scope :user do
    get 'new/user/:id', to: 'users/registrations#show'
  end
  # making /dashboard the root for authenticated users
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  resources :books
  post '/books/:id/borrow', to: 'books#borrow', as: 'borrow_book'
  post '/books/:id/returnbook', to: 'books#returnbook', as: 'returnbook_book'
  # users managing methods used by secretaries
  resources :users, only: %i[index show edit destroy update]

  # courses managing methods
  get '/courses/enrollable', to: 'courses#enrollable'
  resources :courses do
    resources :materials, only: %i[index show destroy new create]
    resources :enrollments, only: :index
    get 'enrollment', to: 'enrollments#show'
    post 'enrollment/:id', to: 'enrollments#add'
    delete 'enrollment/:id', to: 'enrollments#destroy'
  end
  get 'courses/student/:id', to: 'courses#enrolled'
  get 'auth/google_oauth2_drive/callback', to: 'omniauth_callbacks#google_oauth2_drive'

  # Menus
  get '/menus/indexAll', to: 'menus#indexAll'
  get '/reservations', to: 'reservations#index'
  resources :menus do
    # Reservations
    get '/reservations/newGuest', to: 'reservations#newGuest'
    resources :reservations
  end

  # Forms
  resources :forms do
    get 'showResult', to: 'forms#showResult'
  end

  resources :notifications
  post '/notifications/:id/change_status', to: 'notifications#change_status', as: 'change_status_notifications'

  resources :events

  # courses managing methods
  get '/courses/enrollable', to: 'courses#enrollable'
  resources :courses do
    resources :materials, only: %i[index show destroy new create]
    resources :enrollments, only: :index
    get 'enrollment', to: 'enrollments#show'
    post 'enrollment/:id', to: 'enrollments#add'
    delete 'enrollment/:id', to: 'enrollments#destroy'
  end
  get 'courses/student/:id', to: 'courses#enrolled'
  get 'auth/google_oauth2_drive/callback', to: 'omniauth_callbacks#google_oauth2_drive'
  # root for non authenticated users
  root 'home#index'
  resources :menus, only: [:show]
  get '/auth/google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2'
  get 'auth/failure', to: 'omniauth_callbacks#failure'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user! # si deve autenticare
  skip_before_action :authenticate_user!, only: %i[index show] # ma non sempre(visualizzare tutti)

  def index
    authorize! :read, :Unofficial_Event
    authorize! :read, :Official_Event
    @events = Event.all.order('date DESC')
  end

  def new
    if current_user.instance_of? Student
      authorize! :create, :Unofficial_Event
      @event = UnofficialEvent.new
    elsif current_user.instance_of? Secretary
      authorize! :create, :Official_Event
      @event = OfficialEvent.new
    end
  end

  def create
    if current_user.instance_of? Student
      authorize! :create, :Unofficial_Event
      values = params.require(:unofficial_event).permit(:name, :place, :notes, :date)
      @event = UnofficialEvent.new(values)
    elsif current_user.instance_of? Secretary
      authorize! :create, :Official_Event
      values = params.require(:official_event).permit(:name, :place, :notes,:date)
      @event = OfficialEvent.new(values)
    else
      redirect_to events_path
    end
    @event.creator = current_user

    if @event.save
      flash[:notice] = 'success'
      redirect_to events_path
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    authorize! :read, :Unofficial_Event if @event.instance_of? UnofficialEvent
    authorize! :read, :Official_Event if @event.instance_of? OfficialEvent
  end

  def destroy
    @event = Event.find(params[:id])
    authorize! :destroy, :Unofficial_Event unless @event.instance_of? OfficialEvent
    authorize! :destroy, :Official_Event unless @event.instance_of? UnofficialEvent
    if current_user.instance_of? Student
      if @event.creator==current_user
        @event.destroy
        flash[:notice] = 'Unofficial Event deleted'
      else
        flash[:warning]= 'only the event creator can delete it'
        redirect_to events_path
      end
    elsif current_user.instance_of? Secretary
      @event.destroy
      flash[:notice] = 'Unofficial Event deleted'
    else
      flash[:warning]= 'not enough permissions'
      redirect_to events_path
    end
    redirect_to events_path
  end


  def edit
    @event = Event.find(params[:id])
    authorize! :update, :Unofficial_Event if @event.instance_of? UnofficialEvent
    authorize! :update, :Official_Event if @event.instance_of? OfficialEvent
    if @event.instance_of?(UnofficialEvent) && current_user!= @event.creator
      flash[:warning]= 'only the event creator can update it'
      redirect_to events_path
    end
  end

  def update
    @event = Event.find(params[:id])
    authorize! :update, :Unofficial_Event if @event.instance_of? UnofficialEvent
    authorize! :update, :Official_Event if @event.instance_of? OfficialEvent
    if @event.instance_of?(UnofficialEvent) && current_user!= @event.creator
      flash[:warning]= 'only the event creator can update it'
      redirect_to events_path
    end
    data = params.require(:unofficial_event).permit(:name, :place, :notes, :date)  if @event.instance_of? UnofficialEvent
    data = params.require(:official_event).permit(:name, :place, :notes,:date)  if @event.instance_of? OfficialEvent
    res = @event.update(data)
    if res
      flash[:notice] = 'Event updated'
    else
      flash[:warning] = "Can't update Event"
    end
    redirect_to event_path(@event)
  end

  private

  def event_params
    params.require(:event).permit(:name, :place, :notes,:date)
  end

end

app/views/events/_form.html.haml
= form_for @event, url: events_path , html: { method: :post } do |f|
  = f.label :Name
  = f.text_field :name
  %br
  = f.label :Date
  = f.datetime_select :date, default: Time.now, selected: Time.now
  %br
  = f.label :Place
  = f.text_field :place
  %br
  = f.label :Notes
  = f.text_field :notes
  %br
  = f.submit 'Create event'
  %br
  = link_to 'Cancel' , events_path

app/views/events/edit.html.haml
%h2 Edit Event

= form_for @event, url: event_path , html: { method: :put } do |f|
  = f.label :Name
  = f.text_field :name
  %br
  = f.label :Date
  = f.datetime_select :date, prompt: true, order: [:day, :month, :year]
  %br
  = f.label :Place
  = f.text_field :place
  %br
  = f.label :Notes
  = f.text_field :notes
  %br
  = submit_tag 'Update Event'
%br
= link_to 'Cancel', event_path(@event)

app/views/events/index.html.erb
<% content_for :for_head do %>
    <%= stylesheet_link_tag    '/stylesheets/show.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
<% end %>

<body>
<%= month_calendar do |date| %>
    <%= date %>
    <br>
    <% @events.each  do |event| %>
      <% if event.date.to_date==date %>
        <%= event.date.to_time.strftime("%H:%M")%>
        <br>
        <%= link_to "#{event.name}",event_path(event)%>
        <br>
      <% end %>
    <% end %>
<% end %>
<%= link_to "new event", new_event_path %>

<br>
<%= link_to "Home Page",root_path%>
</body>

app/views/events/new.html.haml
%h1 New Event
= render 'form'

app/views/events/show.html.haml
%h2 Details about #{@event.name}
%ul#details
  %li
    type:
    = @event.type
  %li
    name:
    = @event.name
  %li
    place:
    = @event.place
  %li
    date:
    = @event.date.to_date
  %li
    time:
    = @event.date.to_time.strftime("%H:%M")
  %li
    notes:
    = @event.notes
  %li
    creator:
    = User.find(@event.creator.id).username
%br
= link_to "Delete", event_path(@event), :method => :delete
%br
= link_to "Edit", edit_event_path(@event)
%br
= link_to 'Back to Calendar',events_path