config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise users method
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }, path_prefix: 'new'
  devise_scope :user do
    get 'new/user/:id', to: 'users/registrations#show'
  end
  # making /dashboard the root for authenticated users
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  resources :books
  post '/books/:id/borrow', to: 'books#borrow', as: 'borrow_book'
  post '/books/:id/returnbook', to: 'books#returnbook', as: 'returnbook_book'
  # users managing methods used by secretaries
  resources :users, only: %i[index show edit destroy update]

  # courses managing methods
  get '/courses/enrollable', to: 'courses#enrollable'
  resources :courses do
    resources :materials, only: %i[index show destroy new create]
    resources :enrollments, only: :index
    get 'enrollment', to: 'enrollments#show'
    post 'enrollment/:id', to: 'enrollments#add'
    delete 'enrollment/:id', to: 'enrollments#destroy'
  end
  get 'courses/student/:id', to: 'courses#enrolled'
  get 'auth/google_oauth2_drive/callback', to: 'omniauth_callbacks#google_oauth2_drive'

  # Menus
  get '/menus/indexAll', to: 'menus#indexAll'
  get '/reservations', to: 'reservations#index'
  resources :menus do
    # Reservations
    get '/reservations/newGuest', to: 'reservations#newGuest'
    resources :reservations
  end

  # Forms
  resources :forms do
    get 'showResult', to: 'forms#showResult'
  end

  resources :notifications
  post '/notifications/:id/change_status', to: 'notifications#change_status', as: 'change_status_notifications'

  resources :events

  # courses managing methods
  get '/courses/enrollable', to: 'courses#enrollable'
  resources :courses do
    resources :materials, only: %i[index show destroy new create]
    resources :enrollments, only: :index
    get 'enrollment', to: 'enrollments#show'
    post 'enrollment/:id', to: 'enrollments#add'
    delete 'enrollment/:id', to: 'enrollments#destroy'
  end
  get 'courses/student/:id', to: 'courses#enrolled'
  get 'auth/google_oauth2_drive/callback', to: 'omniauth_callbacks#google_oauth2_drive'
  # root for non authenticated users
  root 'home#index'
  resources :menus, only: [:show]
  get '/auth/google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2'
  get 'auth/failure', to: 'omniauth_callbacks#failure'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize! :crud, :Form
  end

  def new
    authorize! :create, :Form
    @form=Form.create
  end

  def edit
    authorize! :update, :Form
    @form = Form.find(params[:id])
  end

  # Permette di mostrare le informazioni di un form nello specifico
  def show
    authorize! :read, :Form
    # Trova il menu da mostrare
    @form = Form.find(params[:id])
  end

  # Permette di mostrare le informazioni sui risultati di un form nello specifico
  def showResult
    authorize! :crud, :Form
    # Trova il menu da mostrare
    @form = Form.find(params[:form_id])
  end

  # Permette di creare nella maniera corretta un nuovo questionario
  def create
    authorize! :create, :Form
    # Ottiene i parametri del questionario passati dalla pagina web
    data = params.require(:form).permit(:dateStart, :dateEnd, :linkToForm, :linkToResult, :canteen)
    # Controlla se la data inserita per il form e' corretta
    if(data[:dateStart].to_date() >= Date.today || data[:dateEnd].to_date() > Date.today)
      # Controlla se i link verso le risorse esterne sono stati inseriti
      if(data[:linkToForm].present? && data[:linkToResult].present?)
        # Imposta l'utente che ha inserito i dati
        # come utente proprietario del form
        data[:canteen] = current_user
        # Controlla se un questionario per questa data e questo pasto esistono già
        unless Form.where('dateStart=? and dateEnd=?', data[:dateStart], data[:dateEnd]).empty?
          # Comunica un messaggio
          flash[:warning] = 'Already existing questionnaire'
          # Reindirizza l'utente
          redirect_to forms_path
          return
        end
        # Crea un istanza del nuovo questionario
        @form = Form.new(data)
        # Salva il questionario nel db
        res = @form.save
        # Controlla se l'operazione e' andata a buon fine
        # e comunica un messaggio
        if res
          flash[:notice] = 'Questionnaire created'
        else
          flash[:warning] = 'Cannot create Questionnaire'
        end
        # Reindirizza l'utente
        redirect_to new_form_path
      else
        # Comunica un messaggio
        flash[:warning] = 'Incorrect inserted links'
      end
    else
      # Comunica un messaggio
      flash[:warning] = 'Incorrect selected dates'
    end
  end

  # Permette di riflettere le modifiche apportate
  # ad un questionario precedentemente creato sul db
  def update
    authorize! :update, :Form
    # Ottiene i parametri del questionario passati dalla pagina web
    data = params.require(:form).permit(:dateStart, :dateEnd, :linkToForm, :linkToResult, :canteen)
    # Controlla se la data inserita per il form e' corretta
    if(data[:dateStart].to_date() >= Date.today || data[:dateEnd].to_date() > Date.today)
      # Controlla se i link verso le risorse esterne sono stati inseriti
      if(data[:linkToForm].present? && data[:linkToResult].present?)
        # Trova il questionario da modificare
        @form = Form.find(params[:id])
        # Aggiorna i dati del questionario
        res = @form.update(data)
        # Controlla se l'operazione e' andata a buon fine
        # e comunica un messaggio
        if res
          flash[:notice] = 'Questionnaire updated'
        else
          flash[:warning] = 'Cannot update questionnaire'
        end
        # Reindirizza l'utente
        redirect_to forms_path
      else
        # Comunica un messaggio
        flash[:warning] = 'Incorrect inserted links'
      end
    else
      # Comunica un messaggio
      flash[:warning] = 'Incorrect selected dates'
    end
  end

  def destroy
    authorize! :destroy, :Form
    # Trova il menu da eliminare
    @form = Form.find(params[:id])
    # Cencella il menu
    @form.destroy
    # Comunica un messaggio
    flash[:notice] = 'Form deleted'
    # Reindirizza l'utente
    redirect_to forms_path
  end

end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/edit.html.haml
%h1= "Update inserted links of google form, Started questionnaire: #{@form.dateStart} -> End: #{@form.dateEnd}"
-# Mostro il Form per inserire il link(embedded) al form
= form_for @form, url: form_path(@form), html: { method: :put } do |f|
  %table
    %tfoot
      %tr
        %td
          = f.label :'Date Start'
          = f.date_field(:dateStart, min: Date.today, required: true)
      %tr
        %td
          = f.label :'Date End'
          = f.date_field(:dateEnd, min: Date.today, required: true)
      %tr
        %td
          = f.label :'Url to embedded google form'
          = f.text_area(:'linkToForm', cols: "150", rows: "2", required: true)
      %tr
        %td
          = f.label :'Url to embedded goole sheet referring to the form'
          = f.text_area(:'linkToResult', cols: "150", rows: "2", required: true)
  =f.submit "Update Questionnaire"
= link_to "Back", forms_path
  

app/views/forms/index.html.haml
%h1 Questionnaires
= link_to "Back", authenticated_root_path
-# Mostro tutti i menu presenti nel db ordinati
-# per data, dal piu' recente al piu' datato
- Form.all.each do |elm|
  %h3= "Questionnaire of #{elm.dateStart}"
  %table#questionnaires
    %thead
      %tr
        %th Date Start
        %th Date End
        %th Form
        %th Form result
    %tfoot
      %tr
        %td= elm.dateStart
        %td= elm.dateEnd
        %td= link_to "Form", form_path(elm.id)
        %td= link_to "Form result", form_showResult_path(elm.id)
        %td= link_to "Edit", edit_form_path(elm.id)
        %td= link_to "Delete", form_path(elm.id), :method => :delete

app/views/forms/new.html.haml
%h1 Insert links to the google form you want to propose to the students
-# Mostro il Form per inserire il link(embedded) al form
%h3 The start and end date indicate only one day, it is not possible to indicate hours and minutes
%h3 Insert the link to the iframe of the google form created for the questionnaire
%h3 Insert the link to the iframe of the google sheet referring to the created questionnaire
%h3= "To get the iframe from google form click on the \"send\" button and then on the \"< >\" icon you will see a url whose first words are <iframe src ..."
%h3= "To get the iframe from google sheet go to File->Publish to the Web and then click on the \"HTML to embed in a page\" chose \"entire document\" end click on \"Publishing\" button now you will see a url whose first words are <iframe src ..."
= form_for @form, url: forms_path, html: { method: :post } do |f|
  %table
    %tfoot
      %tr
        %td
          = f.label :'Date Start'
          = f.date_field(:dateStart, min: Date.today, required: true)
      %tr
        %td
          = f.label :'Date End'
          = f.date_field(:dateEnd, min: Date.today, required: true)
      %tr
        %td
          = f.label :'Url to embedded google form'
          = f.text_area(:'linkToForm', cols: "150", rows: "2", required: true)
      %tr
        %td
          = f.label :'Url to embedded goole sheet referring to the form'
          = f.text_area(:'linkToResult', cols: "150", rows: "2", required: true)
  =f.submit "Add Questionnaire"
= link_to "Back", authenticated_root_path

app/views/forms/show.html.haml
%h1 Answer the questionnaire below
- if current_user.instance_of? Canteen || Secretary
  = link_to "Back", forms_path
- if current_user.instance_of? Student
  = link_to "Back", reservations_path
%br
= raw @form.linkToForm

app/views/forms/showResult.html.haml
%h1 Answers to the proposed questionnaire
= link_to "Back", forms_path
%br
= link_to "Questionnaire", form_path(@form.id)
%br
  = raw @form.linkToResult